version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Specify the default branch so that Dependabot will only create
    # pull requests on this branch
    target-branch: "main"
    # Apply security-related patches only
    pull-request-branch-name:
      separator: "-"
    # Set reviewers and labels for PR
    reviewers:
      - "opencap/maintainers"
    labels:
      - "dependencies"
      - "security"
    # Specify versioning strategy
    versioning-strategy: "auto"
    # Set security updates to be automatically released
    security-updates-only: true
    # Add commit message settings
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "opencap/maintainers"
    labels:
      - "dependencies"
      - "security"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "opencap/maintainers"
    labels:
      - "dependencies"
      - "ci-cd"
