# Docker Compose Test Environment for OpenCap
# Following Semantic Seed BDD/TDD Coding Standards V2.0

version: '3'
services:
  mongodb-test:
    image: mongo:5.0
    container_name: opencap_mongodb_test
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=opencap
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=opencap_test
    volumes:
      - ./test-init-scripts/mongo:/docker-entrypoint-initdb.d
      - mongodb_test_data:/data/db
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-test:
    image: postgres:15-alpine
    container_name: opencap_postgres_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opencap_test
    volumes:
      - ./test-init-scripts/postgres:/docker-entrypoint-initdb.d
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio-test:
    image: minio/minio:latest
    container_name: opencap_minio_test
    command: server /data --console-address ":9001"
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio-setup-test:
    image: minio/mc
    container_name: opencap_minio_setup_test
    depends_on:
      minio-test:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio-test http://minio-test:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio-test/test-bucket;
      /usr/bin/mc policy set public minio-test/test-bucket;
      exit 0;
      "

volumes:
  mongodb_test_data:
    name: opencap_mongodb_test_data
  postgres_test_data:
    name: opencap_postgres_test_data
  minio_test_data:
    name: opencap_minio_test_data
