name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # Only run Docker steps for main branch
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t opencap/api:latest .

      # Docker Hub login with basic approach
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          # First check if credentials exist
          if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
            echo "Docker credentials found, attempting login..."
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            if [ $? -eq 0 ]; then
              echo "Successfully logged into Docker Hub"
            else
              echo "Docker Hub login failed, check credentials"
              # Don't fail the build if Docker login fails
            fi
          else
            echo "Docker Hub credentials not provided, skipping login"
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Push step only runs if login succeeds
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          # Check if we're logged in by checking Docker config
          if grep -q "index.docker.io" ~/.docker/config.json 2>/dev/null; then
            echo "Docker login verified, pushing image..."
            docker push opencap/api:latest
            echo "Successfully pushed image to Docker Hub"
          else
            echo "Not logged in to Docker Hub, skipping push"
          fi
