name: Weekly Security Audit

on:
  schedule:
    # Run every Monday at 2:00 AM UTC
    - cron: '0 2 * * 1'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    # Apply timeout to prevent hung jobs from consuming runner minutes
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm run security:audit:ci

      - name: Run tests
        run: npm run test:ci
        if: always()  # Run even if security audit fails

      - name: Upload security report as artifact
        uses: actions/upload-artifact@v2
        if: always()  # Always upload the security report
        with:
          name: security-audit-report
          path: security-reports/
          retention-days: 90

      - name: Create issue for critical vulnerabilities
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/security-vulnerability.md
          update_existing: true
          search_existing: "Security Audit Failures"
